project:
  type: website
  output-dir: docs
  
description-meta: "Julien Migozzi's personal website."

website:
  title: "Julien Migozzi"
  description: "Website of Julien Migozzi"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications/index.qmd
        text: Research
      # - href: Dissertation.qmd
      #   text: Dissertation
      - href: CV.qmd
    title: false
  page-footer:
    left: "Â© 2022 Julien Migozzi"
    center: "Made with [quarto](https://quarto.org)"
  google-analytics: 
    tracking-id: "G-DM8RWDZ57L"
    storage: none
    anonymize-ip: true

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: 
      - styles.css
      - academicons.css
    fontsize: 1em
    toc: true

